name: zephyrlite
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9.0
  - numpy>=1.19.1
  - pandas>=1.1.0
  - pip>=20.2.2
  - tqdm
  - ipykernel
  - openpyxl
  - pip:
    - pulp>=1.6.0
    - geopandas>=0.10.0
